// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoXd1EOqo-jXOw9UcWN3ggCpd1tJypKlI',
    appId: '1:112046747779:web:ae6f04c5f94364100a6bb6',
    messagingSenderId: '112046747779',
    projectId: 'bimak-aa808',
    authDomain: 'bimak-aa808.firebaseapp.com',
    storageBucket: 'bimak-aa808.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhzhavys6Vta-cCPcosxrrJLAmEhv2T8',
    appId: '1:112046747779:android:4d9d780f49e717e80a6bb6',
    messagingSenderId: '112046747779',
    projectId: 'bimak-aa808',
    storageBucket: 'bimak-aa808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26ugIgeZAUj5KheLLPgcFv8pbJBQP4Zo',
    appId: '1:112046747779:ios:0b3d48116f62db3d0a6bb6',
    messagingSenderId: '112046747779',
    projectId: 'bimak-aa808',
    storageBucket: 'bimak-aa808.appspot.com',
    androidClientId: '112046747779-30h9ntrscdro09u8vveeimdlma7rd6ak.apps.googleusercontent.com',
    iosClientId: '112046747779-3eige8puicn5j4tsq05n5vdg25trplkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bimak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoXd1EOqo-jXOw9UcWN3ggCpd1tJypKlI',
    appId: '1:112046747779:web:f185885dbeafcff00a6bb6',
    messagingSenderId: '112046747779',
    projectId: 'bimak-aa808',
    authDomain: 'bimak-aa808.firebaseapp.com',
    storageBucket: 'bimak-aa808.appspot.com',
  );

}